# Generated by Django 3.1.4 on 2020-12-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoDeLey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fec_ult', models.CharField(blank=True, max_length=20, null=True)),
                ('fec_pres', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=100)),
                ('titulo_del_proyecto', models.TextField()),
            ],
        ),
    ]
