# Generated by Django 3.1.4 on 2020-12-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyectodeley",
            name="autores",
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proyectodeley",
            name="grupo_parlamentario",
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proyectodeley",
            name="legislatura",
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proyectodeley",
            name="periodo",
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proyectodeley",
            name="proponente",
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proyectodeley",
            name="sumilla",
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
