# Generated by Django 3.1.4 on 2020-12-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201231_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectodeley',
            name='autores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyectodeley',
            name='grupo_parlamentario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
